#!/bin/bash

GPU=$(sensors radeon-pci-0100 | grep -oP "([0-9]{1,2}\.[0-9]°C) ")
MOB=$(sensors acpitz-virtual-0 | grep -oP "([0-9]{1,2}\.[0-9]°C) ")
CPU=$(sensors k10temp-pci-00c3 | grep -oP "([0-9]{1,2}\.[0-9]°C) ")

case $BLOCK_BUTTON in
    1)
        echo "CPU: $CPU| MOB: $MOB| GPU: $GPU"
    ;;
    *)
        echo "$CPU"
    ;;
esac
